hard_tabs = false
max_width = 80
blank_lines_upper_bound = 2

wrap_comments = true
comment_width = 80

# brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"

imports_granularity = "Module"
group_imports = "StdExternalCrate"

fn_args_layout = "Compressed"
use_small_heuristics = "Max"

use_field_init_shorthand = true

enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

indent_style = "Block"
format_strings = true
overflow_delimited_expr = true

format_code_in_doc_comments = true

match_arm_blocks = false
match_block_trailing_comma = true
trailing_semicolon = true
